name: Docker Actions

on: [push]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: hello-action
        uses: ./.github/actions/hello-world
        # with:
        #   firstGreeting: "Learning Lab User"
        #   secondGreeting: "Learning Lab User"
        #   thirdGreeting: "Learning Lab User"
